FROM ubuntu

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# get our basic-needs sorted
RUN apt-get update

RUN apt-get -y install apt-utils locales
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

RUN apt-get -y install gcc libffi-dev libssl-dev 
RUN apt-get -y install python3 python3-pip python3-dev
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install --upgrade pip setuptools

RUN pip install awscli --upgrade

RUN apt-get -y install curl
RUN curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
RUN chmod +x /usr/local/bin/ecs-cli

RUN mkdir -p /opt /app
WORKDIR /app

ADD requirements.txt /app
RUN pip install -r requirements.txt

ADD . /app
RUN python3 setup.py install

RUN rm -rf build dist limbo.egg-info

CMD pytest --cov=limbo --cov-report term-missing test

# vim: set expandtab tabstop=4 shiftwidth=4 autoindent smartindent:
